version: '2'

services:
    backend:
        restart: always
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        volumes:
            - .:/app
        environment:
            DJANGO_DEBUG: 'false'
            JUPYTER_URL: http://jupyter:8888
            JUPYTER_WS_URL: 0.0.0.0:8888
            JUPYTER_TOKEN: my_very_secret_token
                